// English texts of the internal pages. The Russian dictionary must have the same shape (see ru.ts).

const s = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const en = {
  nav: {
    label: 'Internal pages',
    admin: 'Admin',
    dashboard: 'Dashboard',
    language: 'Language',
  },
  common: {
    tryAgain: 'Try again',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    cancel: 'Cancel',
    dismiss: 'Dismiss',
    variant: (variant: string) => `Variant ${variant}`,
  },
  units: {
    pp: 'p.p.',
    ppRange: (low: string, high: string) => `${low} to ${high} p.p.`,
    days: (n: number) => `≈ ${n} ${s(n, 'day', 'days')}`,
    hours: (n: number) => `≈ ${n} h`,
    underAnHour: 'less than an hour',
  },
  errors: {
    unreachable: 'The server could not be reached',
    authRequired: 'Authentication required',
    authHint: 'Reload the page and sign in with the admin credentials.',
    versionConflictHint: 'Increase "version" in the config, validate and save again.',
    requestFailed: (status: number) => `Request failed (HTTP ${status})`,
  },
  admin: {
    documentTitle: (funnelId: string) => `Admin · ${funnelId}`,
    loading: (funnelId: string) => `Loading ${funnelId}…`,
    funnel: 'Funnel',
    active: (version: number) => `Active v${version}`,
    noActiveVersion: 'No active version',
    noReleaseNote: 'No release note',
    previewTitle: 'Preview as a new session',
    previewHint: 'Forced-variant sessions are QA traffic and are left out of the A/B comparison.',
    versions: 'Versions',
    rollback: 'Roll back',
    rollbackTo: (version: number) => `Roll back to v${version}`,
    rollbackUnavailable: 'No previously published version to return to',
    rollbackHint: 'Rollback re-activates the previously published version for new sessions. Sessions already started stay on their version.',
    releaseLog: 'Release log',
    publishTitle: (version: number) => `Publish v${version}?`,
    publishBody: (version: number) =>
      `New sessions will start on v${version}. Sessions already in progress stay on the version they started with.`,
    publishLabel: (version: number) => `Publish v${version}`,
    nowActive: (version: number) => `v${version} is now active.`,
    previouslyActive: (version: number) => `Previously active: v${version}.`,
    rollbackTitle: (version: number) => `Roll back to v${version}?`,
    rollbackBody: (target: number, active: number | null) =>
      `New sessions will start on v${target} again. Sessions already started on v${active} keep running on v${active}.`,
    rolledBack: (from: number, to: number) => `Rolled back from v${from} to v${to}.`,
    previewOpened: (version: number, variant: string) => `Preview of v${version} · ${variant} opened in a new tab.`,
    previewReady: (version: number, variant: string) => `Preview of v${version} · ${variant} is ready.`,
    previewLink: 'Open the preview',
  },
  versions: {
    empty: 'No versions stored yet. Upload a config below.',
    version: 'Version',
    experiment: 'Experiment',
    releaseNote: 'Release note',
    created: 'Created',
    sessions: 'Sessions',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    stored: 'Stored',
    viewJson: 'View JSON',
    hideJson: 'Hide JSON',
    publish: 'Publish',
    preview: (variant: string) => `Preview ${variant}`,
    previewHint:
      'Preview opens a stored version as a separate session before it is published. Preview sessions never count in analytics.',
    loadingConfig: (version: number) => `Loading v${version}…`,
    copy: 'Copy',
    copied: 'Copied',
    configOf: (version: number) => `Config of version ${version}`,
  },
  publish: {
    title: 'Publish a new version',
    chooseFile: 'Choose file…',
    startFromActive: 'Start from active',
    startFrom: (version: number) => `Start from v${version}`,
    hint: 'Choose a .json file, drop it on the editor or paste a config. Validation stores nothing.',
    configLabel: 'Config JSON',
    invalidJson: 'Invalid JSON',
    invalidJsonError: (message: string) => `Invalid JSON: ${message}`,
    validate: 'Validate',
    validating: 'Validating…',
    saveDraft: 'Save as draft',
    saving: 'Saving…',
    saveAndPublish: 'Save and publish',
    publishing: 'Publishing…',
    outdated: 'The config changed after validation. Validate again to save it.',
    confirmTitle: (version: number) => `Save and publish v${version}?`,
    alreadyActive: (version: number) => `v${version} was already active.`,
    storedAndPublished: 'Stored as a new version and published.',
    identicalPublished: 'This exact config was already stored, so it was published as is.',
    savedDraft: (version: number) => `v${version} saved as a draft.`,
    alreadyStored: (version: number) => `v${version} is already stored with this exact config.`,
    publishLater: 'Publish it from the versions table when it is ready.',
    valid: 'Valid',
    errorCount: (n: number) => `${n} ${s(n, 'error', 'errors')}`,
    warningCount: (n: number) => `${n} ${s(n, 'warning', 'warnings')}`,
    newVersion: (version: number) => `New version v${version}`,
    identical: (version: number) => `v${version} is already stored with identical content`,
    conflict: (version: number) => `v${version} already exists with different content. Increase "version" to store this config.`,
    nothingToCompare: 'No active version to compare with.',
  },
  diff: {
    title: (from: number, to: number) => `Changes against active v${from} → v${to}`,
    noChange: 'No change',
    experiment: 'Experiment',
    newExperiment: 'new experiment id: results are compared separately',
    sameExperiment: 'Same experiment id',
    steps: 'Steps',
    results: 'Results',
    events: 'Events',
    operators: 'Operators',
    orderChanged: 'order changed',
  },
  releaseLog: {
    empty: 'No releases yet.',
    publish: 'publish',
    rollback: 'rollback',
    none: 'none',
  },
  dash: {
    title: 'Funnel analytics',
    loading: 'Loading analytics…',
    signInTitle: 'Sign in required',
    signInBody: 'The dashboard is for the team only. Reload the page and enter the admin credentials.',
    reload: 'Reload',
    loadFailed: 'Could not load analytics',
    emptyTitle: 'No events yet',
    emptyBody: 'Add demo data to run simulated visitors through the funnel, or open the funnel yourself, then refresh.',
    signInBanner: 'Sign in required: reload the page and enter the admin credentials.',
    refreshFailed: (message: string) => `Refresh failed: ${message}`,
    noSessions: (version: number) => `No sessions in v${version} match these filters`,
    noSessionsHint: 'Try another campaign or include QA overrides.',
    abTitle: (version: number) => `A/B test · v${version}`,
    funnelTitle: 'Step funnel',
    resultsTitle: 'Results',
    eventsTitle: 'Events',
    versionsTitle: 'Versions',
    qualityTitle: 'Data quality',
  },
  demo: {
    add: 'Add demo data',
    adding: 'Generating…',
    addHint: 'Runs 200 more simulated visitors through the active version via the public API',
    added: (sessions: number, version: number, completed: number) =>
      `Added ${sessions} demo sessions on v${version}, ${completed} reached the result.`,
    failed: (message: string) => `Demo data: ${message}`,
  },
  filters: {
    label: 'Filters',
    version: 'Version',
    latest: ' (latest)',
    campaign: 'Campaign',
    allCampaigns: 'All campaigns',
    noCampaign: '(none)',
    includeOverrides: 'Include QA overrides',
    updated: (time: string) => `Updated ${time}`,
  },
  ab: {
    metrics: { ctaConversion: 'CTA conversion', resultRate: 'Result rate', ctr: 'CTR' },
    hypothesisLabel: 'Hypothesis:',
    hypothesis: (topic: string, control: string, treatment: string) =>
      `changing the ${topic} in ${treatment} raises CTA conversion over ${control}`,
    primaryLabel: 'Primary metric:',
    primary: 'CTA conversion = sessions with a CTA click ÷ started sessions.',
    onlyVariants: (variants: string) => `Only ${variants} has sessions with these filters, so there is nothing to compare.`,
    variantName: (variant: string) => `variant ${variant}`,
    noSessionsYet: 'no sessions yet',
    ci: (interval: string) => `95% CI ${interval}`,
    started: 'Started',
    reachedResult: 'Reached result',
    ctaClicks: 'CTA clicks',
    control: 'control',
    treatment: 'treatment',
    noData: 'No data',
    noDataText: 'One of the variants has no sessions yet, so there is nothing to compare.',
    significant: 'Significant',
    significantText: (treatment: string, better: boolean, control: string) =>
      `${treatment} converts ${better ? 'better' : 'worse'} than ${control}, and the difference is statistically significant (p < 0.05).`,
    notSignificant: 'Not significant',
    smallSampleText: (required: string, smaller: string) =>
      `The sample is too small to conclude: a difference of this size needs about ${required} sessions per variant, and the smaller variant has ${smaller}.`,
    noDifferenceText: (treatment: string, control: string) =>
      `No significant difference between ${treatment} and ${control} at the current sample size.`,
    mismatch: 'Split mismatch',
    mismatchText: (p: string) =>
      `The traffic split does not match the configured weights (p = ${p}), so this comparison is not reliable. Check the variant assignment before reading the result.`,
    verdictTitle: (treatment: string, control: string) => `CTA conversion, ${treatment} vs ${control}`,
    diffCi: '95% CI of the difference',
    relativeLift: 'Relative lift',
    pValue: 'p-value',
    sampleSize: 'Sample size',
    sampleNeeded: (n: string) => `≈${n} sessions per variant needed`,
    targetFallback: 'a 5 p.p. difference',
    targetObserved: 'the observed difference',
    sampleNote: (target: string, control: string, controlCount: string, treatment: string, treatmentCount: string) =>
      `to detect ${target} with 80% power at α = 0.05; ${control} has ${controlCount}, ${treatment} has ${treatmentCount}`,
    split: 'Traffic split',
    splitExpected: (expected: string) => `expected ${expected}`,
    splitUnchecked: 'too few randomly assigned sessions to test it',
    splitMismatch: (p: string) => `sample ratio mismatch, p = ${p}`,
    splitOk: (p: string) => `matches the weights, p = ${p}`,
    eta: 'Time to sample',
    etaReached: 'Sample size reached',
    etaReachedNote: (control: string, treatment: string) => `${control} and ${treatment} both have the required sessions`,
    etaRate: (rate: string) => `at ≈ ${rate} sessions a day: the average since the version's first session, over at least a day`,
    etaStopped: 'Not collecting',
    etaStoppedNote: 'this version is no longer active, so no new sessions arrive',
    etaUnknownNote: 'not enough data to estimate',
    secondary: 'Secondary metrics',
    metric: 'Metric',
    difference: 'Difference',
    ciShort: '95% CI',
    result: 'Result',
  },
  funnel: {
    lead: {
      toNext: 'To next',
      toNextText:
        ' = sessions that got past the step ÷ sessions that reached it, so a conditional step has its own denominator. ',
      dropoff: 'Drop-off',
      dropoffText:
        ' = sessions whose furthest step it was and that never saw a result (on the result step: left while the result was loading).',
    },
    started: (n: string) => `${n} started`,
    noConfig: 'The config of this version is unavailable, so its steps cannot be laid out.',
    step: 'Step',
    reached: 'Reached',
    fromStart: 'From start',
    toNext: 'To next',
    dropoff: 'Drop-off',
    conditional: 'conditional',
    conditionalHint: 'Shown only to sessions whose answers meet its visibleWhen condition',
    reachedOf: (reached: string, started: string) => `${reached} of ${started} started sessions`,
    worst: 'Biggest drop-off',
  },
  results: {
    withResult: (n: string) => `${n} sessions with a result`,
    none: 'No result viewed yet.',
    share: (n: string, total: string) => `${n} of ${total} sessions`,
  },
  events: {
    event: 'Event',
    sessions: 'Sessions',
    events: 'Events',
  },
  dashVersions: {
    note: 'Versions ran at different times on different traffic, so this table is context, not a controlled comparison. Use the A/B test within a version to judge a change.',
    version: 'Version',
    experiment: 'Experiment',
    firstSeen: 'First seen',
    lastSeen: 'Last seen',
    started: 'Started',
    resultRate: 'Result rate',
    ctr: 'CTR',
    ctaConversion: 'CTA conversion',
  },
  quality: {
    reasons: {
      invalid_payload: 'Malformed event',
      unknown_session: 'Unknown session',
      server_only_event: 'Server-only event sent by a client',
      event_not_allowed: 'Not allowed by the pinned version',
      unknown_step: "Step not in the session's variant",
      invalid_properties: 'Invalid properties',
    },
    scope: 'all versions, current campaign',
    events: 'Events',
    eventsDetail: (scope: string) => `unique event ids, ${scope}`,
    sessions: 'Sessions',
    overrides: 'QA override sessions',
    overridesDetail: (scope: string, included: boolean) => `${scope}, ${included ? 'included in' : 'excluded from'} the numbers`,
    previews: 'Preview sessions',
    previewsDetail: 'admin previews, never counted',
    rejected: 'Rejected events',
    rejectedDetail: 'refused at ingestion',
    noneRejected: 'No events were rejected.',
    reason: 'Reason',
    code: 'Code',
  },
};

export type Messages = typeof en;
