import type { Messages } from './en';

/** 1 день, 2 дня, 5 дней. */
function plural(n: number, one: string, few: string, many: string): string {
  const mod10 = n % 10;
  const mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;
  return many;
}

export const ru: Messages = {
  nav: {
    label: 'Внутренние страницы',
    admin: 'Админка',
    dashboard: 'Дашборд',
    language: 'Язык',
  },
  common: {
    tryAgain: 'Повторить',
    refresh: 'Обновить',
    refreshing: 'Обновляем…',
    cancel: 'Отмена',
    dismiss: 'Закрыть',
    variant: (variant) => `Вариант ${variant}`,
  },
  units: {
    pp: 'п.п.',
    ppRange: (low, high) => `от ${low} до ${high} п.п.`,
    days: (n) => `≈ ${n} ${plural(n, 'день', 'дня', 'дней')}`,
    hours: (n) => `≈ ${n} ч`,
    underAnHour: 'меньше часа',
  },
  errors: {
    unreachable: 'Сервер недоступен',
    authRequired: 'Нужна авторизация',
    authHint: 'Перезагрузите страницу и войдите с данными администратора.',
    versionConflictHint: 'Увеличьте "version" в конфиге, проверьте и сохраните снова.',
    requestFailed: (status) => `Запрос не выполнен (HTTP ${status})`,
  },
  admin: {
    documentTitle: (funnelId) => `Админка · ${funnelId}`,
    loading: (funnelId) => `Загружаем ${funnelId}…`,
    funnel: 'Воронка',
    active: (version) => `Активна v${version}`,
    noActiveVersion: 'Нет активной версии',
    noReleaseNote: 'Без описания релиза',
    previewTitle: 'Открыть как новую сессию',
    previewHint: 'Сессии с принудительным вариантом считаются тестовыми и не входят в A/B-сравнение.',
    versions: 'Версии',
    rollback: 'Откатить',
    rollbackTo: (version) => `Откатить на v${version}`,
    rollbackUnavailable: 'Нет ранее опубликованной версии, на которую можно вернуться',
    rollbackHint: 'Откат снова делает активной ранее опубликованную версию для новых сессий. Уже начатые сессии остаются на своей версии.',
    releaseLog: 'Журнал релизов',
    publishTitle: (version) => `Опубликовать v${version}?`,
    publishBody: (version) => `Новые сессии начнутся на v${version}. Уже начатые сессии останутся на той версии, с которой начали.`,
    publishLabel: (version) => `Опубликовать v${version}`,
    nowActive: (version) => `v${version} теперь активна.`,
    previouslyActive: (version) => `До этого была активна v${version}.`,
    rollbackTitle: (version) => `Откатить на v${version}?`,
    rollbackBody: (target, active) =>
      `Новые сессии снова начнутся на v${target}. Сессии, начатые на v${active}, продолжат работать на v${active}.`,
    rolledBack: (from, to) => `Откат с v${from} на v${to} выполнен.`,
    previewOpened: (version, variant) => `Превью v${version} · ${variant} открыто в новой вкладке.`,
    previewReady: (version, variant) => `Превью v${version} · ${variant} готово.`,
    previewLink: 'Открыть превью',
  },
  versions: {
    empty: 'Сохранённых версий пока нет. Загрузите конфиг ниже.',
    version: 'Версия',
    experiment: 'Эксперимент',
    releaseNote: 'Описание релиза',
    created: 'Создана',
    sessions: 'Сессии',
    status: 'Статус',
    actions: 'Действия',
    active: 'Активна',
    stored: 'Сохранена',
    viewJson: 'Показать JSON',
    hideJson: 'Скрыть JSON',
    publish: 'Опубликовать',
    preview: (variant) => `Превью ${variant}`,
    previewHint: 'Превью открывает сохранённую версию отдельной сессией ещё до публикации. Превью-сессии не попадают в аналитику.',
    loadingConfig: (version) => `Загружаем v${version}…`,
    copy: 'Копировать',
    copied: 'Скопировано',
    configOf: (version) => `Конфиг версии ${version}`,
  },
  publish: {
    title: 'Публикация новой версии',
    chooseFile: 'Выбрать файл…',
    startFromActive: 'Взять активную',
    startFrom: (version) => `Взять v${version}`,
    hint: 'Выберите файл .json, перетащите его в редактор или вставьте конфиг. Проверка ничего не сохраняет.',
    configLabel: 'JSON конфига',
    invalidJson: 'Некорректный JSON',
    invalidJsonError: (message) => `Некорректный JSON: ${message}`,
    validate: 'Проверить',
    validating: 'Проверяем…',
    saveDraft: 'Сохранить черновик',
    saving: 'Сохраняем…',
    saveAndPublish: 'Сохранить и опубликовать',
    publishing: 'Публикуем…',
    outdated: 'Конфиг изменился после проверки. Проверьте его снова, чтобы сохранить.',
    confirmTitle: (version) => `Сохранить и опубликовать v${version}?`,
    alreadyActive: (version) => `v${version} уже была активна.`,
    storedAndPublished: 'Сохранена как новая версия и опубликована.',
    identicalPublished: 'Точно такой конфиг уже был сохранён, поэтому он опубликован как есть.',
    savedDraft: (version) => `v${version} сохранена как черновик.`,
    alreadyStored: (version) => `v${version} уже сохранена с точно таким же конфигом.`,
    publishLater: 'Опубликуйте её из таблицы версий, когда она будет готова.',
    valid: 'Корректен',
    errorCount: (n) => `${n} ${plural(n, 'ошибка', 'ошибки', 'ошибок')}`,
    warningCount: (n) => `${n} ${plural(n, 'предупреждение', 'предупреждения', 'предупреждений')}`,
    newVersion: (version) => `Новая версия v${version}`,
    identical: (version) => `v${version} уже сохранена с тем же содержимым`,
    conflict: (version) => `v${version} уже есть с другим содержимым. Увеличьте "version", чтобы сохранить этот конфиг.`,
    nothingToCompare: 'Нет активной версии для сравнения.',
  },
  diff: {
    title: (from, to) => `Изменения относительно активной v${from} → v${to}`,
    noChange: 'Без изменений',
    experiment: 'Эксперимент',
    newExperiment: 'новый id эксперимента: результаты сравниваются отдельно',
    sameExperiment: 'Тот же id эксперимента',
    steps: 'Шаги',
    results: 'Результаты',
    events: 'События',
    operators: 'Операторы',
    orderChanged: 'порядок изменён',
  },
  releaseLog: {
    empty: 'Релизов пока нет.',
    publish: 'публикация',
    rollback: 'откат',
    none: 'нет',
  },
  dash: {
    title: 'Аналитика воронки',
    loading: 'Загружаем аналитику…',
    signInTitle: 'Нужно войти',
    signInBody: 'Дашборд доступен только команде. Перезагрузите страницу и введите данные администратора.',
    reload: 'Перезагрузить',
    loadFailed: 'Не удалось загрузить аналитику',
    emptyTitle: 'Событий пока нет',
    emptyBody:
      'Добавьте демоданные, чтобы прогнать через воронку симулированных посетителей, или пройдите воронку сами и обновите страницу.',
    signInBanner: 'Нужно войти: перезагрузите страницу и введите данные администратора.',
    refreshFailed: (message) => `Не удалось обновить: ${message}`,
    noSessions: (version) => `В v${version} нет сессий под эти фильтры`,
    noSessionsHint: 'Выберите другую кампанию или включите QA-сессии.',
    abTitle: (version) => `A/B-тест · v${version}`,
    funnelTitle: 'Воронка по шагам',
    resultsTitle: 'Результаты',
    eventsTitle: 'События',
    versionsTitle: 'Версии',
    qualityTitle: 'Качество данных',
  },
  demo: {
    add: 'Добавить демоданные',
    adding: 'Генерируем…',
    addHint: 'Прогоняет ещё 200 симулированных посетителей через активную версию по публичному API',
    added: (sessions, version, completed) => `Добавлено демосессий: ${sessions} на v${version}, до результата дошли ${completed}.`,
    failed: (message) => `Демоданные: ${message}`,
  },
  filters: {
    label: 'Фильтры',
    version: 'Версия',
    latest: ' (последняя)',
    campaign: 'Кампания',
    allCampaigns: 'Все кампании',
    noCampaign: '(без кампании)',
    includeOverrides: 'Учитывать QA-сессии',
    updated: (time) => `Обновлено ${time}`,
  },
  ab: {
    metrics: { ctaConversion: 'Конверсия в CTA', resultRate: 'Доходимость до результата', ctr: 'CTR' },
    hypothesisLabel: 'Гипотеза:',
    hypothesis: (topic, control, treatment) => `изменение «${topic}» в ${treatment} повышает конверсию в CTA относительно ${control}`,
    primaryLabel: 'Основная метрика:',
    primary: 'конверсия в CTA = сессии с кликом по CTA ÷ начатые сессии.',
    onlyVariants: (variants) => `Под эти фильтры сессии есть только у ${variants}, сравнивать нечего.`,
    variantName: (variant) => `варианта ${variant}`,
    noSessionsYet: 'сессий пока нет',
    ci: (interval) => `95% ДИ ${interval}`,
    started: 'Начали',
    reachedResult: 'Дошли до результата',
    ctaClicks: 'Клики по CTA',
    control: 'контроль',
    treatment: 'тест',
    noData: 'Нет данных',
    noDataText: 'У одного из вариантов пока нет сессий, сравнивать нечего.',
    significant: 'Значимо',
    significantText: (treatment, better, control) =>
      `${treatment} конвертирует ${better ? 'лучше' : 'хуже'}, чем ${control}, и разница статистически значима (p < 0.05).`,
    notSignificant: 'Не значимо',
    smallSampleText: (required, smaller) =>
      `Выборка слишком мала для вывода: для разницы такого размера нужно около ${required} сессий на вариант, а в меньшем варианте ${smaller}.`,
    noDifferenceText: (treatment, control) => `При текущем объёме выборки значимой разницы между ${treatment} и ${control} нет.`,
    mismatch: 'Сбой сплита',
    mismatchText: (p) =>
      `Распределение трафика не совпадает с весами из конфига (p = ${p}), поэтому сравнению нельзя доверять. Сначала проверьте назначение вариантов.`,
    verdictTitle: (treatment, control) => `Конверсия в CTA, ${treatment} против ${control}`,
    diffCi: '95% ДИ разницы',
    relativeLift: 'Относительный прирост',
    pValue: 'p-value',
    sampleSize: 'Объём выборки',
    sampleNeeded: (n) => `нужно ≈${n} сессий на вариант`,
    targetFallback: 'разницу в 5 п.п.',
    targetObserved: 'наблюдаемую разницу',
    sampleNote: (target, control, controlCount, treatment, treatmentCount) =>
      `чтобы заметить ${target} с мощностью 80% при α = 0.05; в ${control} ${controlCount}, в ${treatment} ${treatmentCount}`,
    split: 'Сплит трафика',
    splitExpected: (expected) => `ожидалось ${expected}`,
    splitUnchecked: 'мало случайно распределённых сессий для проверки',
    splitMismatch: (p) => `расхождение с весами, p = ${p}`,
    splitOk: (p) => `совпадает с весами, p = ${p}`,
    eta: 'До нужной выборки',
    etaReached: 'Выборка набрана',
    etaReachedNote: (control, treatment) => `в ${control} и ${treatment} уже есть нужное число сессий`,
    etaRate: (rate) => `при ≈ ${rate} сессий в день: среднее с первой сессии версии, не меньше чем за сутки`,
    etaStopped: 'Сбор остановлен',
    etaStoppedNote: 'версия больше не активна, новые сессии не приходят',
    etaUnknownNote: 'мало данных для оценки',
    secondary: 'Вторичные метрики',
    metric: 'Метрика',
    difference: 'Разница',
    ciShort: '95% ДИ',
    result: 'Итог',
  },
  funnel: {
    lead: {
      toNext: 'Дальше',
      toNextText: ' = сессии, прошедшие шаг ÷ сессии, дошедшие до него, поэтому у условного шага свой знаменатель. ',
      dropoff: 'Отвал',
      dropoffText:
        ' = сессии, для которых шаг стал последним и которые так и не увидели результат (на шаге результата: ушли, пока результат загружался).',
    },
    started: (n) => `начали: ${n}`,
    noConfig: 'Конфиг этой версии недоступен, поэтому шаги не построить.',
    step: 'Шаг',
    reached: 'Дошли',
    fromStart: 'От старта',
    toNext: 'Дальше',
    dropoff: 'Отвал',
    conditional: 'условный',
    conditionalHint: 'Показывается только сессиям, чьи ответы подходят под условие visibleWhen',
    reachedOf: (reached, started) => `${reached} из ${started} начатых сессий`,
    worst: 'Наибольший отвал',
    order: 'Порядок',
    orders: { steps: 'По шагам', dropoff: 'По отвалу', reached: 'По охвату' },
  },
  results: {
    withResult: (n) => `сессий с результатом: ${n}`,
    none: 'Результат пока никто не видел.',
    share: (n, total) => `${n} из ${total} сессий`,
  },
  events: {
    event: 'Событие',
    sessions: 'Сессии',
    events: 'События',
  },
  dashVersions: {
    note: 'Версии работали в разное время на разном трафике, поэтому таблица даёт контекст, а не контролируемое сравнение. Изменение оценивайте по A/B-тесту внутри версии.',
    version: 'Версия',
    experiment: 'Эксперимент',
    firstSeen: 'Первое событие',
    lastSeen: 'Последнее событие',
    started: 'Начали',
    resultRate: 'Доходимость',
    ctr: 'CTR',
    ctaConversion: 'Конверсия в CTA',
  },
  quality: {
    reasons: {
      invalid_payload: 'Некорректный формат события',
      unknown_session: 'Неизвестная сессия',
      server_only_event: 'Серверное событие от клиента',
      event_not_allowed: 'Не разрешено закреплённой версией',
      unknown_step: 'Шага нет в варианте сессии',
      invalid_properties: 'Некорректные свойства',
    },
    scope: 'все версии, текущая кампания',
    events: 'События',
    eventsDetail: (scope) => `уникальные event_id, ${scope}`,
    sessions: 'Сессии',
    overrides: 'QA-сессии',
    overridesDetail: (scope, included) => `${scope}, ${included ? 'учтены' : 'не учтены'} в цифрах`,
    previews: 'Превью-сессии',
    previewsDetail: 'превью из админки, не учитываются',
    rejected: 'Отклонённые события',
    rejectedDetail: 'отклонены при приёме',
    noneRejected: 'Отклонённых событий нет.',
    reason: 'Причина',
    code: 'Код',
  },
};
