import type {
  CreateSessionRequest,
  ResultResponse,
  SaveStateRequest,
  SaveStateResponse,
  SessionResponse,
} from '@funnel/contracts';
import type { Answers } from '@funnel/engine';
import { http } from './http';

const sessionUrl = (sessionId: string) => `/api/sessions/${encodeURIComponent(sessionId)}`;

export function getSession(sessionId: string): Promise<SessionResponse> {
  return http<SessionResponse>('GET', sessionUrl(sessionId));
}

/** Idempotent: the id is generated by the client, so a retried request returns the session created by the first one. */
export function createSession(sessionId: string, body: CreateSessionRequest): Promise<SessionResponse> {
  return http<SessionResponse>('PUT', sessionUrl(sessionId), body);
}

/** `keepalive` lets a save started right before the tab closes complete. */
export function saveState(sessionId: string, body: SaveStateRequest): Promise<SaveStateResponse> {
  return http<SaveStateResponse>('PUT', `${sessionUrl(sessionId)}/state`, body, { keepalive: true });
}

export function requestResult(sessionId: string, answers: Answers): Promise<ResultResponse> {
  return http<ResultResponse>('POST', `${sessionUrl(sessionId)}/result`, { answers });
}
